// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSG9O5tJiPm_oUzXA0Qur_OEs4fpt853k',
    appId: '1:679301881723:web:b5a8609d2e70ec36a7e7de',
    messagingSenderId: '679301881723',
    projectId: 'my-flutter-afl',
    authDomain: 'my-flutter-afl.firebaseapp.com',
    storageBucket: 'my-flutter-afl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClH3DobFo70Nm04b8ske8vYujA-bmgyDg',
    appId: '1:679301881723:android:18b893c1ecb09b1ba7e7de',
    messagingSenderId: '679301881723',
    projectId: 'my-flutter-afl',
    storageBucket: 'my-flutter-afl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaKjC0id-i0lb4UoyZxc_ygNWZU2C6VbQ',
    appId: '1:679301881723:ios:b00e995281ed9d5ca7e7de',
    messagingSenderId: '679301881723',
    projectId: 'my-flutter-afl',
    storageBucket: 'my-flutter-afl.firebasestorage.app',
    iosBundleId: 'au.utas.edu.jayanie.aflapp.aflApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaKjC0id-i0lb4UoyZxc_ygNWZU2C6VbQ',
    appId: '1:679301881723:ios:b00e995281ed9d5ca7e7de',
    messagingSenderId: '679301881723',
    projectId: 'my-flutter-afl',
    storageBucket: 'my-flutter-afl.firebasestorage.app',
    iosBundleId: 'au.utas.edu.jayanie.aflapp.aflApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSG9O5tJiPm_oUzXA0Qur_OEs4fpt853k',
    appId: '1:679301881723:web:8890844988cbd2bda7e7de',
    messagingSenderId: '679301881723',
    projectId: 'my-flutter-afl',
    authDomain: 'my-flutter-afl.firebaseapp.com',
    storageBucket: 'my-flutter-afl.firebasestorage.app',
  );

}